/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author YULIUS
 */
public class Toko_buah extends javax.swing.JFrame {

    /**
     * Creates new form Toko_buah
     */
    public Toko_buah() {
        initComponents();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup2.add(jRadioButton3);
        buttonGroup2.add(jRadioButton4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        txt_kg1 = new javax.swing.JTextField();
        txt_kg2 = new javax.swing.JTextField();
        txt_kg3 = new javax.swing.JTextField();
        txt_kg4 = new javax.swing.JTextField();
        txt_kg5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        totalBayar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_harga5 = new javax.swing.JTextField();
        txt_harga4 = new javax.swing.JTextField();
        txt_harga3 = new javax.swing.JTextField();
        txt_harga2 = new javax.swing.JTextField();
        txt_harga1 = new javax.swing.JTextField();
        txt_diskon5 = new javax.swing.JTextField();
        txt_diskon4 = new javax.swing.JTextField();
        txt_diskon3 = new javax.swing.JTextField();
        txt_diskon2 = new javax.swing.JTextField();
        txt_diskon1 = new javax.swing.JTextField();
        jb5 = new javax.swing.JTextField();
        jb4 = new javax.swing.JTextField();
        jb3 = new javax.swing.JTextField();
        jb2 = new javax.swing.JTextField();
        jb1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBox1.setText("Jeruk");

        jCheckBox2.setText("Pepaya");

        jCheckBox3.setText("Apel");

        jCheckBox4.setText("Anggur");

        jCheckBox5.setText("Salak");

        jLabel1.setText("Bayar :");

        jLabel2.setText("Status Pelanggan :");

        jRadioButton1.setText("Cash");

        jRadioButton2.setText("Kartu Kredit (Potongan 2%)");

        jRadioButton3.setText("Member (Discont 5%)");

        jRadioButton4.setText("Bukan Member");

        jButton1.setText("TOTAL BAYAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BERSIH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Buah");

        jLabel4.setText("Kg");

        jLabel5.setText("Harga");

        jLabel6.setText("Discont (%)");

        jLabel7.setText("Jumlah Bayar");

        txt_diskon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diskon4ActionPerformed(evt);
            }
        });

        txt_diskon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diskon3ActionPerformed(evt);
            }
        });

        txt_diskon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diskon2ActionPerformed(evt);
            }
        });

        txt_diskon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diskon1ActionPerformed(evt);
            }
        });

        jLabel8.setText("TOKO BUAH ABC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox5)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_kg1)
                                    .addComponent(txt_kg2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_kg3)
                                    .addComponent(txt_kg4)
                                    .addComponent(txt_kg5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_harga1)
                                    .addComponent(txt_harga2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_harga3)
                                    .addComponent(txt_harga4)
                                    .addComponent(txt_harga5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_diskon1)
                                    .addComponent(txt_diskon2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_diskon3)
                                    .addComponent(txt_diskon4)
                                    .addComponent(txt_diskon5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jb1)
                                    .addComponent(jb2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb3)
                                    .addComponent(jb4)
                                    .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCheckBox2)
                                            .addComponent(txt_kg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCheckBox3)
                                            .addComponent(txt_kg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox4))
                                    .addComponent(txt_kg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_kg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_harga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_harga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addComponent(txt_harga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_harga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_harga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_diskon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_diskon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addComponent(txt_diskon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_diskon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_diskon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1))
                .addGap(1, 1, 1)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            totalBayar.setText(String.valueOf(a));
        }
        if(jCheckBox2.isSelected()){
            int a = Integer.parseInt(jb2.getText());
            totalBayar.setText(String.valueOf(a));
        }
        if(jCheckBox3.isSelected()){
            int a = Integer.parseInt(jb3.getText());
            totalBayar.setText(String.valueOf(a));
        }
        if(jCheckBox4.isSelected()){
            int a = Integer.parseInt(jb4.getText());
            totalBayar.setText(String.valueOf(a));
        }
        if(jCheckBox5.isSelected()){
            int a = Integer.parseInt(jb5.getText());
            totalBayar.setText(String.valueOf(a));
        }
        
        if(jCheckBox1.isSelected() & jCheckBox2.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            int b = Integer.parseInt(jb2.getText());
            int hasil = a+b;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox1.isSelected() & jCheckBox3.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            int b = Integer.parseInt(jb3.getText());
            int hasil = a+b;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox1.isSelected() & jCheckBox4.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            int b = Integer.parseInt(jb4.getText());
            int hasil = a+b;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox1.isSelected() & jCheckBox5.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            int b = Integer.parseInt(jb5.getText());
            int hasil = a+b;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox2.isSelected() & jCheckBox3.isSelected()){
            int a = Integer.parseInt(jb2.getText());
            int b = Integer.parseInt(jb3.getText());
            int hasil = a+b;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox2.isSelected() & jCheckBox4.isSelected()){
            int a = Integer.parseInt(jb2.getText());
            int b = Integer.parseInt(jb4.getText());
            int hasil = a+b;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox2.isSelected() & jCheckBox5.isSelected()){
            int a = Integer.parseInt(jb2.getText());
            int b = Integer.parseInt(jb5.getText());
            int hasil = a+b;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox3.isSelected() & jCheckBox4.isSelected()){
            int a = Integer.parseInt(jb3.getText());
            int b = Integer.parseInt(jb4.getText());
            int hasil = a+b;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox3.isSelected() & jCheckBox5.isSelected()){
            int a = Integer.parseInt(jb3.getText());
            int b = Integer.parseInt(jb5.getText());
            int hasil = a+b;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox4.isSelected() & jCheckBox5.isSelected()){
            int a = Integer.parseInt(jb4.getText());
            int b = Integer.parseInt(jb5.getText());
            int hasil = a+b;
            totalBayar.setText(String.valueOf(hasil));
        }
        
        
        if(jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox3.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            int b = Integer.parseInt(jb2.getText());
            int c = Integer.parseInt(jb3.getText());
            int hasil = a+b+c;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox4.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            int b = Integer.parseInt(jb2.getText());
            int c = Integer.parseInt(jb4.getText());
            int hasil = a+b+c;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox5.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            int b = Integer.parseInt(jb2.getText());
            int c = Integer.parseInt(jb5.getText());
            int hasil = a+b+c;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox2.isSelected() & jCheckBox3.isSelected() & jCheckBox4.isSelected()){
            int a = Integer.parseInt(jb2.getText());
            int b = Integer.parseInt(jb3.getText());
            int c = Integer.parseInt(jb4.getText());
            int hasil = a+b+c;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox2.isSelected() & jCheckBox4.isSelected() & jCheckBox5.isSelected()){
            int a = Integer.parseInt(jb2.getText());
            int b = Integer.parseInt(jb4.getText());
            int c = Integer.parseInt(jb5.getText());
            int hasil = a+b+c;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox3.isSelected() & jCheckBox4.isSelected() & jCheckBox5.isSelected()){
            int a = Integer.parseInt(jb3.getText());
            int b = Integer.parseInt(jb4.getText());
            int c = Integer.parseInt(jb5.getText());
            int hasil = a+b+c;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox3.isSelected() & jCheckBox4.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            int b = Integer.parseInt(jb2.getText());
            int c = Integer.parseInt(jb3.getText());
            int d = Integer.parseInt(jb4.getText());
            int hasil = a+b+c+d;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox3.isSelected() & jCheckBox5.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            int b = Integer.parseInt(jb2.getText());
            int c = Integer.parseInt(jb3.getText());
            int d = Integer.parseInt(jb5.getText());
            int hasil = a+b+c+d;
            totalBayar.setText(String.valueOf(hasil));
        }
        if(jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox3.isSelected() & jCheckBox4.isSelected() & jCheckBox5.isSelected()){
            int a = Integer.parseInt(jb1.getText());
            int b = Integer.parseInt(jb2.getText());
            int c = Integer.parseInt(jb3.getText());
            int d = Integer.parseInt(jb4.getText());
            int e = Integer.parseInt(jb5.getText());
            int hasil = a+b+c+d+e;
            totalBayar.setText(String.valueOf(hasil));
        }
        
        
        int hasil1, hasil2, cas, disc, bayar;
        if(jRadioButton1.isSelected() & jRadioButton3.isSelected()){
            int a = Integer.parseInt(totalBayar.getText());
            hasil1 = a;
            hasil2 = hasil1 * 5 / 100;
            bayar  = hasil1 - hasil2;
            totalBayar.setText(String.valueOf(bayar));
        }
        if(jRadioButton1.isSelected() & jRadioButton4.isSelected()){
            int a = Integer.parseInt(totalBayar.getText());
            totalBayar.setText(String.valueOf(a));
        }
        if(jRadioButton2.isSelected() & jRadioButton3.isSelected()){
            int a = Integer.parseInt(totalBayar.getText());
            hasil1 = a;
            hasil2 = hasil1 * 2 / 100;
            cas = hasil1 + hasil2;
            disc = cas * 5 / 100;
            bayar  = cas - disc;
            totalBayar.setText(String.valueOf(bayar));
        }
        if(jRadioButton2.isSelected() & jRadioButton4.isSelected()){
            int a = Integer.parseInt(totalBayar.getText());
            hasil1 = a;
            hasil2 = hasil1 * 2 / 100;
            bayar  = hasil1 + hasil2;
            totalBayar.setText(String.valueOf(bayar));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_diskon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diskon1ActionPerformed
        // TODO add your handling code here:
        int hasil1, hasil2, bayar;
        int a = Integer.parseInt(txt_kg1.getText());
        int b = Integer.parseInt(txt_harga1.getText());
        int disc = Integer.parseInt(txt_diskon1.getText());
        hasil1 = a*b;
        hasil2 = hasil1 * disc / 100;
        bayar = hasil1 - hasil2;
        jb1.setText(String.valueOf(bayar));
    }//GEN-LAST:event_txt_diskon1ActionPerformed

    private void txt_diskon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diskon2ActionPerformed
        // TODO add your handling code here:
        int hasil1, hasil2, bayar;
        int a = Integer.parseInt(txt_kg2.getText());
        int b = Integer.parseInt(txt_harga2.getText());
        int disc = Integer.parseInt(txt_diskon2.getText());
        hasil1 = a*b;
        hasil2 = hasil1 * disc / 100;
        bayar = hasil1 - hasil2;
        jb2.setText(String.valueOf(bayar));
    }//GEN-LAST:event_txt_diskon2ActionPerformed

    private void txt_diskon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diskon3ActionPerformed
        // TODO add your handling code here:
        int hasil1, hasil2, bayar;
        int a = Integer.parseInt(txt_kg3.getText());
        int b = Integer.parseInt(txt_harga3.getText());
        int disc = Integer.parseInt(txt_diskon3.getText());
        hasil1 = a*b;
        hasil2 = hasil1 * disc / 100;
        bayar = hasil1 - hasil2;
        jb3.setText(String.valueOf(bayar));
    }//GEN-LAST:event_txt_diskon3ActionPerformed

    private void txt_diskon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diskon4ActionPerformed
        // TODO add your handling code here:
        int hasil1, hasil2, bayar;
        int a = Integer.parseInt(txt_kg4.getText());
        int b = Integer.parseInt(txt_harga4.getText());
        int disc = Integer.parseInt(txt_diskon4.getText());
        hasil1 = a*b;
        hasil2 = hasil1 * disc / 100;
        bayar = hasil1 - hasil2;
        jb4.setText(String.valueOf(bayar));
    }//GEN-LAST:event_txt_diskon4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txt_kg1.setText("");
        txt_kg2.setText("");
        txt_kg3.setText("");
        txt_kg4.setText("");
        txt_kg5.setText("");
        txt_harga1.setText("");
        txt_harga2.setText("");
        txt_harga3.setText("");
        txt_harga4.setText("");
        txt_harga5.setText("");
        txt_diskon1.setText("");
        txt_diskon2.setText("");
        txt_diskon3.setText("");
        txt_diskon4.setText("");
        txt_diskon5.setText("");
        jb1.setText("");
        jb2.setText("");
        jb3.setText("");
        jb4.setText("");
        jb5.setText("");
        totalBayar.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toko_buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toko_buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toko_buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toko_buah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toko_buah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jb1;
    private javax.swing.JTextField jb2;
    private javax.swing.JTextField jb3;
    private javax.swing.JTextField jb4;
    private javax.swing.JTextField jb5;
    private javax.swing.JTextField totalBayar;
    private javax.swing.JTextField txt_diskon1;
    private javax.swing.JTextField txt_diskon2;
    private javax.swing.JTextField txt_diskon3;
    private javax.swing.JTextField txt_diskon4;
    private javax.swing.JTextField txt_diskon5;
    private javax.swing.JTextField txt_harga1;
    private javax.swing.JTextField txt_harga2;
    private javax.swing.JTextField txt_harga3;
    private javax.swing.JTextField txt_harga4;
    private javax.swing.JTextField txt_harga5;
    private javax.swing.JTextField txt_kg1;
    private javax.swing.JTextField txt_kg2;
    private javax.swing.JTextField txt_kg3;
    private javax.swing.JTextField txt_kg4;
    private javax.swing.JTextField txt_kg5;
    // End of variables declaration//GEN-END:variables
}
